kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: mysql-statefulset
  namespace: mysql
spec:
  replicas: 3
  serviceName: mysql-service
  selector:
    matchLabels:
      app: mysql

  template:
     metadata:
       labels:
          app: mysql
     spec:
        containers:
        - name: mysql
          image: mysql:latest
          ports:
          - containerPort: 3306
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: mysql-configmap
                key: MYSQL_DATABASE
          volumeMounts:
          - name: mysql-data
            mountPath: /var/lib/mysql
  volumeClaimTemplates:
      - metadata:
           name: mysql-data
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
               storage: 1Gi
